production: # This is the Amazon RDS instance db.
  adapter: mysql2 
  database: the_company
  host: or-ohev-zion.cwqkw32fyhbb.eu-west-1.rds.amazonaws.com
  username: master
  password: v676fzxG

development: # This is the mysql db via mysql-workbench located locally on my computer..
  adapter: mysql2   
  encoding: utf8
  database: New_Company
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

test: # This is the Amazon RDS instance db.
  adapter: mysql2
  host: 
  reconnect: false
  database: the_company
  username: master
  password: v676fzxG
