production:
  adapter: mysql2 # here goes the amazaon RDS properties.
  encoding: utf8
  database: New_Company
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql2
  encoding: utf8
  database: New_Company
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock

test: # also here, if you want...
  adapter: mysql2
  host: ohev-zion.cx8usb91m0zi.eu-west-1.rds.amazonaws.com
  reconnect: false
  database: the_company
  username: master
  password: orisking16
